routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Cerveceria;
use App\Cerveza;
use App\Evento;
use App\Editor;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Ruta de inicio
Route::get('/', function(){
    return redirect()->route('inicio');
});

Route::get('/inicio', function() {

    $cervezas = Cerveza::inRandomOrder()->take(10)->get();
    $cervezas = $cervezas->all();

    return view('layouts.content', compact('cervezas'));
})->name('inicio');



//Rutas para el cliente
Route::get('passwd/{cliente}', 'ClienteController@passwd')->name('cliente.passwd');
Route::get('cliente/compra', 'ClienteController@compra')->name('cliente.compra');
Route::get('cliente/checkout/domicilio', 'ClienteController@checkout_dom')->name('cliente.checkout_dom');
Route::get('cliente/checkout/envio', 'ClienteController@checkout_env')->name('cliente.checkout_env');
Route::get('cliente/checkout/pago', 'ClienteController@checkout_pag')->name('cliente.checkout_pag');
Route::get('cliente/checkout/revision', 'ClienteController@checkout_rev')->name('cliente.checkout_rev');
Route::patch('cliente/{id}/password', 'ClienteController@changePassword')->name('cliente.changePassword');
Route::resource('cliente', 'ClienteController');

//Ruta para domicilio
Route::resource('domicilio', 'DomicilioController');

//Ruta para tarjeta
Route::resource('tarjeta', 'TarjetaController');

//Rutas para editor
//Route::get('/editor/updateList', 'EditorController@updateList')->name('editor.updateList');
//Route::get('/editor/deleteList', 'EditorController@deleteList')->name('editor.deleteList');
//Route::post("/editor/scopeName", "EditorController@scopeName")->name("editor.scopeName");
//Route::post("/editor/scopeDelete", "EditorController@scopeDelete")->name("editor.scopeDelete");
//Route::get('editor/login', 'Auth\EditorLoginController@showLoginForm');
//Route::post('editor/login', 'Auth\EditorLoginController@login')->name('editor.login');
//Route::post('editor/logout', 'Auth\EditorLoginController@logout')->name('editor.logout');
//Route::resource('editor', 'EditorController');

//Rutas para libro
//Route::get('/cerveza/update', 'LibroController@updateList')->name('cerveza.updateList');
//Route::get('/cerveza/delete', 'LibroController@deleteList')->name('cerveza.deleteList');

//Route::post("/cerveza/scopeName", "CervezaController@scopeName")->name("cerveza.scopeName");
//Route::post("/cerveza/scopeDelete", "CervezaController@scopeDelete")->name("cerveza.scopeDelete");

Route::resource('libro', 'LibroController');

//Rutas para pedidos
Route::get('/crearPedido', 'PedidoController@crearPedido')->name('pedido.store');
Route::get('/pedidos', 'PedidoController@showOrders')->name('pedido.showOrders');
Route::get('/cliente/{cliente}/{pedido}', 'PedidoController@showOneOrder')->name('pedido.showOneOrder');

//Ruta para enviar correo
//Route::get('/send-mail', 'PedidoController@sendEmail')->name('pedido.sendEmail');


//Rutas para la tienda
Route::get('tienda/cervezas', 'ShopController@porCerveceria')->name('tienda.porCerveceria');
Route::get('estilo/{estilo}', 'ShopController@porEstilo')->name('tienda.porEstilo');
Route::post('tienda/buscar', 'ShopController@buscar')->name('tienda.buscar');
Route::resource('tienda', 'ShopController');

//Ruta para contacto
Route::get('/contacto', function() {

    return view('layouts_cliente.contacto');
});

//Rutsa para el carrito de compras
Route::resource('cart', 'CartController');
Route::post('cart/coupon', 'CartController@apply')->name('cart.apply');
Route::get('vaciar', function(){
    Cart::clear();
});

//Rutas para Eventos
Route::get('/evento/delete/{id}', 'EventoController@delete')->name('evento.delete');
Route::get('/evento/delete', 'EventoController@deleteList')->name('evento.deleteList');
Route::post("/evento/scopeName", "EventoController@scopeName")->name("evento.scopeName");
Route::post("/evento/scopeDelete", "EventoController@scopeDelete")->name("evento.scopeDelete");
Route::resource('evento', 'EventoController');

//Rutas para Reportes
Route::post('/reporte/nuevo', 'ReporteController@createReport')->name('reporte.nuevo');
Route::get('/reporte/create/pdf', 'ReporteController@createPdf')->name('reporte.pdf');
Route::get('/reporte/view', 'ReporteController@view')->name('reporte.view');
Route::get('/reporte/select/{reporte}', 'ReporteController@select')->name('reporte.select');
Route::get('/reportes', 'ReporteController@viewReports')->name('reporte.list');
Route::resource('reporte', 'ReporteController');

resources/views/partials/email.blade.php
<!DOCTYPE html>
<html>
  <head>
      <title>Tienda Online Cata</title>
  </head>
  <body>
      <h1>{{ $details['title'] }}</h1>
      <p>{{ $details['body'] }}</p>   
      <p>Gracias por su preferencia</p>
  </body>
</html>

resources/views/partials/login-client.blade.php
<div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ingresar</h5>
        <button type="button" data-dismiss="modal" aria-label="Close" class="close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{route('login')}}" method="POST">
          @csrf
          <div class="form-group">
            <input id="email-modal" type="text" placeholder="Correo electrónico" class="form-control" name="correo" required>
            @error('email-modal')
              <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
          <div class="form-group">
            <input id="password-modal" type="password" placeholder="Contraseña" class="form-control" name="password" required>
            @error('password-modal')
              <div class="alert alert-danger">{{ $message }}</div>
            @enderror
          </div>
          <p class="text-center">
            <button class="btn btn-primary"><i class="fa fa-sign-in"></i>Ingresar</button>
          </p>
        </form>
        <p class="text-center text-muted">¿Aún no has creado tu cuenta?</p>
        <p class="text-center text-muted">
          <a href="{{route('register')}}">
            <strong>¡Regístrate ahora!</strong>
          </a> Es rápido y fácil y podrás tener acceso a descuentos especiales y mucho más.
        </p>
      </div>
    </div>
  </div>
</div>

resources/views/partials/login-register.blade.php
<div class="container">
  <div class="row">
    <div class="col-lg-6 offer mb-3 mb-lg-0"></div>
    <div class="col-lg-6 text-center text-lg-right">
    @guest
      <ul class="menu list-inline mb-0">
        <li class="list-inline-item"><a href="{{route('login')}}" data-toggle="modal" data-target="#login-modal">Ingresar</a></li>
        <li class="list-inline-item"><a href="{{route('register')}}">Registrar</a></li>
        <li class="list-inline-item"><a href="contact.html">Contacto</a></li>
      </ul>
    @else
      <ul class="menu list-inline mb-0">
        <li class="list-inline-item"><a>Bienvenido(a) {{Auth::user()->nombre}}</a></li>
        <li class="list-inline-item"><a href="{{route('cliente.show', [Auth::user()->id])}}">Mi Cuenta</a></li>
        <li class="list-inline-item"><a href="{{route('logout')}}"
                                      onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();">Salir</a></li>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
        </form>
      </ul>
    @endguest
    </div>
  </div>
</div>

resources/views/partials/logo.blade.php
@guest
  <a href="{{route('inicio')}}" class="navbar-brand home">
    <img src="/img/cata-logo.png" alt="CATA logo" class="d-none d-md-inline-block">
    <img src="/img/cata-logo-sm.png" alt="CATA logo" class="d-inline-block d-md-none">
    <span class="sr-only">CATA - go to homepage</span>
  </a>
@else
  <a href="{{route('cliente.index')}}" class="navbar-brand home">
    <img src="/img/cata-logo.png" alt="Obaju logo" class="d-none d-md-inline-block">
    <img src="/img/cata-logo-sm.png" alt="Obaju logo" class="d-inline-block d-md-none">
    <span class="sr-only">CATA - go to homepage</span>
  </a>
@endguest
<div class="navbar-buttons">
  <button type="button" data-toggle="collapse" data-target="#navigation" class="btn btn-outline-secondary navbar-toggler">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-align-justify"></i>
  </button>
  <button type="button" data-toggle="collapse" data-target="#search" class="btn btn-outline-secondary navbar-toggler">
    <span class="sr-only">Toggle search</span>
    <i class="fa fa-search"></i>
  </button>
  @auth
    <a href="{{route('cart.index')}}" class="btn btn-outline-secondary navbar-toggler">
      <i class="fa fa-shopping-cart"></i>
    </a>
  @endauth
</div>

resources/views/partials/might-also-like.blade.php
<div class="row same-height-row">
  <div class="col-lg-3 col-md-6">
    <div class="box same-height">
      <h3>Estos productos podrían gustarte</h3>
    </div>
  </div>
  @foreach($sugerencias as $sugerencia)
    <div class="col-md-3 col-sm-6">
      <div class="product same-height">
        <div class="flip-container">
          <div class="flipper">
            <div class="front"><a href="{{route('tienda.show', $sugerencia->id)}}"><img src="{{$sugerencia->imagen}}" alt="{{$sugerencia->nombre}}" class="img-fluid"></a></div>
            <div class="back"><a href="{{route('tienda.show', $sugerencia->id)}}"><img src="{{$sugerencia->imagen}}" alt="{{$sugerencia->nombre}}" class="img-fluid"></a></div>
          </div>
        </div>
        <a href="{{route('tienda.show', $sugerencia->id)}}" class="invisible">
          <img src="{{$sugerencia->imagen}}" alt="" class="img-fluid">
        </a>
        <div class="text">
          <h3>{{$sugerencia->nombre}}</h3>
          <p class="price">${{$sugerencia->precio}}</p>
        </div>
      </div>
    </div>
  @endforeach
</div>

resources/views/partials/navbar-buttons.blade.php
<div class="navbar-buttons d-flex justify-content-end">
  <div id="search-not-mobile" class="navbar-collapse collapse"></div>
  <a data-toggle="collapse" href="#search" class="btn navbar-btn btn-primary d-none d-lg-inline-block">
    <span class="sr-only">Toggle search</span>
    <i class="fa fa-search"></i>
  </a>
  @auth
    <div id="basket-overview" class="navbar-collapse collapse d-none d-lg-block">
      <a href="{{route('cart.index')}}" class="btn btn-primary navbar-btn">
        <i class="fa fa-shopping-cart"></i>
        <span>{{Cart::getTotalQuantity()}}</span>
      </a>
    </div>
  @endauth
</div>

resources/views/partials/pdf-report.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CATA online</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">

    <!--Rutas para mostrar el pdf con formato -->
    <link rel="stylesheet" href="{{asset('css2/style.default.premium.css')}}">
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/vendor2/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/vendor2/font-awesome/css/font-awesome.min.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="/https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/css2/style.default.premium.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/css/custom.css">
    <!-- Main File-->
    <script src="/js/front2.js"></script>
  </head>
  <body>
    <div class="card">
      <div class="card-header">
        <p><h4>Reporte</h4></p>
        <p><strong>Periodo: </strong>{{$datos['fecha_inicio']}} - {{$datos['fecha_final']}}</p>
        <p><strong>Generado por: </strong>{{App\Editor::where('id', $reporte->editor_id)->first()->nombre}} {{App\Editor::where('id', $reporte->editor_id)->first()->apepat}}</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-sm" id="reporte">
            <thead>
              <tr>
                <th>Id</th>
                <th>Nombre de cerveza</th>
                <th>Cantidad vendida</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              @for($i=0; $i<$datos['total_cervezas']; $i++)
                <tr>
                  <th scope="row">{{$datos['cervezas_id'][$i]}}</th>
                  <td>{{$datos['cervezas_nombre'][$i]}}</td>
                  <td>{{$datos['cervezas_cantidad'][$i]}}</td>
                  <td>${{$datos['cervezas_monto'][$i]}}.00</td>
                </tr>
              @endfor
              <tr>
                <th scope="row"></th>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <th scope="row"></th>
                <td></td>
                <td>Productos vendidos: </td>
                <td>{{$datos['total_cervezas_vendidas']}}</td>
              </tr>
              <tr>
                <th scope="row"></th>
                <td></td>
                <td>Total vendido: </td>
                <td>${{$datos['monto_vendido']}}.00</td>
              </tr>
              <tr>
                <th scope="row"></th>
                <td></td>
                <td>Envíos normales: </td>
                <td>{{$datos['envios_normales']}}</td>
              </tr>
              <tr>
                <th scope="row"></th>
                <td></td>
                <td>Envíos exprés: </td>
                <td>{{$datos['envios_expres']}}</td>
              </tr>
              <tr>
                <th scope="row"></th>
                <td></td>
                <td>Pagos con tarjeta: </td>
                <td>{{$datos['pagos_tarjeta']}}</td>
              </tr>
              <tr>
                <th scope="row"></th>
                <td></td>
                <td>Pagos con Paypal: </td>
                <td>{{$datos['pagos_paypal']}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

resources/views/partials/search.blade.php
<div id="search" class="collapse">
  <div class="container">
    <form role="search" class="ml-auto" action="{{route('tienda.buscar')}}" method="POST">
      @csrf
      <div class="input-group">
        <input type="text" placeholder="Buscar" class="form-control" name="buscar">
        <div class="input-group-append">
          <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </form>
  </div>
</div>