routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Cerveceria;
use App\Cerveza;
use App\Evento;
use App\Editor;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Ruta de inicio
Route::get('/', function(){
    return redirect()->route('inicio');
});

Route::get('/inicio', function() {

    $cervezas = Cerveza::inRandomOrder()->take(10)->get();
    $cervezas = $cervezas->all();

    return view('layouts.content', compact('cervezas'));
})->name('inicio');



//Rutas para el cliente
Route::get('passwd/{cliente}', 'ClienteController@passwd')->name('cliente.passwd');
Route::get('cliente/compra', 'ClienteController@compra')->name('cliente.compra');
Route::get('cliente/checkout/domicilio', 'ClienteController@checkout_dom')->name('cliente.checkout_dom');
Route::get('cliente/checkout/envio', 'ClienteController@checkout_env')->name('cliente.checkout_env');
Route::get('cliente/checkout/pago', 'ClienteController@checkout_pag')->name('cliente.checkout_pag');
Route::get('cliente/checkout/revision', 'ClienteController@checkout_rev')->name('cliente.checkout_rev');
Route::patch('cliente/{id}/password', 'ClienteController@changePassword')->name('cliente.changePassword');
Route::resource('cliente', 'ClienteController');

//Ruta para domicilio
Route::resource('domicilio', 'DomicilioController');

//Ruta para tarjeta
Route::resource('tarjeta', 'TarjetaController');

//Rutas para editor
//Route::get('/editor/updateList', 'EditorController@updateList')->name('editor.updateList');
//Route::get('/editor/deleteList', 'EditorController@deleteList')->name('editor.deleteList');
//Route::post("/editor/scopeName", "EditorController@scopeName")->name("editor.scopeName");
//Route::post("/editor/scopeDelete", "EditorController@scopeDelete")->name("editor.scopeDelete");
//Route::get('editor/login', 'Auth\EditorLoginController@showLoginForm');
//Route::post('editor/login', 'Auth\EditorLoginController@login')->name('editor.login');
//Route::post('editor/logout', 'Auth\EditorLoginController@logout')->name('editor.logout');
//Route::resource('editor', 'EditorController');

//Rutas para libro
//Route::get('/cerveza/update', 'LibroController@updateList')->name('cerveza.updateList');
//Route::get('/cerveza/delete', 'LibroController@deleteList')->name('cerveza.deleteList');

//Route::post("/cerveza/scopeName", "CervezaController@scopeName")->name("cerveza.scopeName");
//Route::post("/cerveza/scopeDelete", "CervezaController@scopeDelete")->name("cerveza.scopeDelete");

Route::resource('libro', 'LibroController');

//Rutas para pedidos
Route::get('/crearPedido', 'PedidoController@crearPedido')->name('pedido.store');
Route::get('/pedidos', 'PedidoController@showOrders')->name('pedido.showOrders');
Route::get('/cliente/{cliente}/{pedido}', 'PedidoController@showOneOrder')->name('pedido.showOneOrder');

//Ruta para enviar correo
//Route::get('/send-mail', 'PedidoController@sendEmail')->name('pedido.sendEmail');


//Rutas para la tienda
Route::get('tienda/cervezas', 'ShopController@porCerveceria')->name('tienda.porCerveceria');
Route::get('estilo/{estilo}', 'ShopController@porEstilo')->name('tienda.porEstilo');
Route::post('tienda/buscar', 'ShopController@buscar')->name('tienda.buscar');
Route::resource('tienda', 'ShopController');

//Ruta para contacto
Route::get('/contacto', function() {

    return view('layouts_cliente.contacto');
});

//Rutsa para el carrito de compras
Route::resource('cart', 'CartController');
Route::post('cart/coupon', 'CartController@apply')->name('cart.apply');
Route::get('vaciar', function(){
    Cart::clear();
});

//Rutas para Eventos
Route::get('/evento/delete/{id}', 'EventoController@delete')->name('evento.delete');
Route::get('/evento/delete', 'EventoController@deleteList')->name('evento.deleteList');
Route::post("/evento/scopeName", "EventoController@scopeName")->name("evento.scopeName");
Route::post("/evento/scopeDelete", "EventoController@scopeDelete")->name("evento.scopeDelete");
Route::resource('evento', 'EventoController');

//Rutas para Reportes
Route::post('/reporte/nuevo', 'ReporteController@createReport')->name('reporte.nuevo');
Route::get('/reporte/create/pdf', 'ReporteController@createPdf')->name('reporte.pdf');
Route::get('/reporte/view', 'ReporteController@view')->name('reporte.view');
Route::get('/reporte/select/{reporte}', 'ReporteController@select')->name('reporte.select');
Route::get('/reportes', 'ReporteController@viewReports')->name('reporte.list');
Route::resource('reporte', 'ReporteController');

resources/views/layouts_editor/editorAuthorize.blade.php
<html lang="en"><head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Forbidden</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .code {
                border-right: 2px solid;
                font-size: 26px;
                padding: 0 15px 0 15px;
                text-align: center;
            }

            .message {
                font-size: 18px;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="code">
                403            </div>

            <div class="message" style="padding: 10px;">
                This action is unauthorized.            </div>
        </div>
    

</body></html>

resources/views/layouts_editor/editorCrearReporte.blade.php
@extends('layouts_editor.editorMenu')

@section('content')
<div class="breadcrumb-holder">
  <div class="container-fluid">
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{route('editor.index')}}">Inicio</a></li>
      <li class="breadcrumb-item active">Reportes       </li>
    </ul>
  </div>
</div>
<section>
  <div class="container-fluid top-custom">
    <header> 
      <h1 class="h3 display">Reportes            </h1>
    </header>
    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-header">
            <h4>Creación de reporte de ventas</h4>
          </div>
          <div class="card-body">
            <p>Selecciona el periodo en que quieras generar el reporte de ventas y la fecha de inicio</p>
            <form id="test" action="{{ route('reporte.nuevo') }}" method="POST">
              @csrf
              <input type="hidden" name="editor_id" value="{{auth()->guard('editor')->user()->id}}">
              <select name="periodo" class="col-md-4">
                <option value="semanal">Semanal</option>
                <option value="quincenal">Quincenal</option>
                <option value="mensual">Mensual</option>
              </select>
              <br><br>
              <input type="text" placeholder="AAAA-MM-DD" class="col-md-6" name= "fecha_inicio">
              <br><br>
              <p>
                <button data-style="zoom-in" class="btn btn-primary ladda-button"
                        onclick="event.preventDefault();
                        document.getElementById('test').submit();">
                  <span class="ladda-label">Generar reporte</span>
                </button>
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Loading buttons-->
<script src="/vendor2/ladda/spin.min.js"></script>
<script src="/vendor2/ladda/ladda.min.js"></script>
<script src="/js/components-ladda.js"></script>
@endsection

resources/views/layouts_editor/editorCreate.blade.php
@extends('layouts_editor.editorMenu')
@section('content')

<div class="container-fluid">
      <!-- Breadcrumb-->
      <div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('editor.index')}}">Inicio</a></li>
            <li class="breadcrumb-item active">Agregar Editor  </li>
          </ul>
        </div>
      </div>
      <section class="forms">
        <div class="container-fluid">
          <!-- Page Header-->
          <header> 
            <h1 class="h3 display">Nuevo Editor  </h1>
          </header>
        <form action="/editor" method="POST" role="form" enctype="multipart/form-data">
            @csrf
          <div class="col-lg-12">
              <div class="card">
                <div class="card-header d-flex align-items-center">
                  <h4>Formulario Para Crear Un Nuevo Editor</h4>
                </div>

                <div class="card-body">
                  <!--- Nombre Editor-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Nombre: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="nombre" required>
                        @error('nombre')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                    <!--- Apellido Paterno Editor-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Apellido Paterno: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="apepat" required>
                        @error('apepat')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                    <!--- Apellido Materno Editor-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Materno Paterno: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="apemat" required>
                        @error('apemat')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                   <!--- Fecha Nacimiento-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Fecha Nacimiento:</label>
                      <div class="col-sm-10">
                        <input type="date" class="form-control" name="fecnac" required>
                        @error('fecnac')
                                    <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                      </div>
                    </div>
                    <!--- Correo Editor-->
                     <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Correo Electronico: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="correo" required>
                        @error('correo')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                     <!--- Correo Editor-->
                     <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Contraseña: </label>
                      <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" required>
                        @error('password')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                 

                    
                    <div class="form-group row">
                      <div class="col-sm-4 offset-sm-2">
                        <a class="btn btn-outline-danger" href="{{route('evento.index')}}" role="button">Cancelar</a>
                        <button type="submit" class="btn btn-outline-success">Añadir Editor</button>
                      </div>
                    </div>
                 </div>
              </div>
            </div>
        </form>
    </div>
      </div>
  </body>
</html>
@endsection


      

resources/views/layouts_editor/editorEdit.blade.php
@extends('layouts_editor.editorMenu')
@section('content')
<div class="container-fluid">
      <!-- Breadcrumb-->
      <div class="breadcrumb-holder">
        <div class="container-fluid">
          <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('editor.index')}}">Inicio</a></li>
            <li class="breadcrumb-item active">Actualizar / Editor  </li>
          </ul>
        </div>
      </div>
      <section class="forms">
        <div class="container-fluid">
          <!-- Page Header-->
          <header> 
            <h1 class="h3 display">Actualizar Editor  </h1>
          </header>
        <form action="/editor/{{$editor->id}}" method="POST" role="form" enctype="multipart/form-data">
            @csrf
          <div class="col-lg-12">
              <div class="card">
                <div class="card-header d-flex align-items-center">
                  <h4>Datos del editor</h4>
                </div>

                <div class="card-body">
                  <!--- Nombre Editor-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Nombre: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="nombre" value="{{$editor->nombre}}" required>
                        <input type="hidden" name="_method" value="PUT">     
                        @error('nombre')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                    <!--- Apellido Paterno Editor-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Apellido Paterno: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="apepat" value="{{$editor->apepat}}" required>
                        @error('apepat')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                    <!--- Apellido Materno Editor-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Materno Paterno: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="apemat" value="{{$editor->apemat}}" required>
                        @error('apemat')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>
                   <!--- Fecha Nacimiento-->
                    <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Fecha Nacimiento:</label>
                      <div class="col-sm-10">
                        <input type="date" class="form-control" name="fecnac" value="{{$editor->fecnac}}" required>
                        @error('fecnac')
                                    <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                      </div>
                    </div>
                    <!--- Correo Editor-->
                     <div class="form-group row">
                      <label class="col-sm-2 form-control-label">Correo Electronico: </label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="correo" value="{{$editor->correo}}" required>
                        @error('correo')
                                    <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                      </div>
                    </div>

                    
                    <div class="form-group row">
                      <div class="col-sm-4 offset-sm-2">
                        <a class="btn btn-outline-danger" href="{{route('evento.index')}}" role="button">Cancelar</a>
                        <button type="submit" class="btn btn-outline-success">Actualizar Editor</button>
                      </div>
                    </div>
                 </div>
              </div>
            </div>
        </form>
    </div>
      </div>
  </body>
</html>
@endsection


      

resources/views/layouts_editor/editorInicioContenido.blade.php
@extends('layouts_editor.editorMenu')

@section('content')
<section>
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
              <h4>Bienvenido(a) a CATA Designer</h4>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/layouts_editor/editorMenu.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CATA online</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/vendor2/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/vendor2/font-awesome/css/font-awesome.min.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="/css2/fontastic.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="/https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="/css2/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="/vendor2/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/css2/style.default.premium.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="/img/favicon.ico">
    <!-- Ladda-->
    <link rel="stylesheet" href="/vendor2/ladda/ladda-themeless.min.css">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="/css2/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- JavaScript files-->
    <script src="/vendor2/jquery/jquery.min.js"></script>
    <script src="/vendor2/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="/vendor2/jquery.cookie/jquery.cookie.js"> </script>
    <script src="/vendor2/chart.js/Chart.min.js"></script>
    <script src="/vendor2/jquery-validation/jquery.validate.min.js"></script>
    <script src="/vendor2/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Main File-->
    <script src="/js/charts-home.js"></script>
    <script src="/js/front2.js"></script>
  </head>
  <body>
    <!-- Side Navbar -->
    <nav class="side-navbar">
      <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">
          <!-- User Info-->
          <div class="sidenav-header-inner text-center"><a href="pages-profile.html"></a>
            <h2 class="h5">{{auth()->guard('editor')->user()->nombre}}</h2>
            <span>Editor {{auth()->guard('editor')->user()->id}}</span>
          </div>
          <!-- Small Brand information, appears on minimized sidebar-->
          <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong>C</strong><strong class="text-primary">D</strong></a></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
          <h5 class="sidenav-heading">Menú</h5>
          <ul id="side-main-menu" class="side-menu list-unstyled">
            <!-- Editores -->             
            <li><a href="{{route('editor.index')}}"><i class="icon-home"></i>Inicio</a></li>
            @if(auth()->guard('editor')->user()->can('isAdmin', $admin))
              <li><a href="#opcionesEditor" aria-expanded="false" data-toggle="collapse"> <i class="icon-user"></i>Editores</a>
                <ul id="opcionesEditor" class="collapse list-unstyled ">
                  <li><a href="{{route('editor.create')}}">Nuevo Editor</a></li>
                  <li><a href="{{route('editor.updateList')}}">Actualizar Editor</a></li>
                  <li><a href="{{route('editor.deleteList')}}">Borrar Editor</a></li>
                </ul>
              </li>
            @endif
            <!-- Eventos -->                
            <li><a href="#opcionesEvento" aria-expanded="false" data-toggle="collapse"> <i class="icon-picture"></i>Eventos</a>
              <ul id="opcionesEvento" class="collapse list-unstyled ">
                <li><a href="{{route('evento.create')}}">Nuevo evento</a></li>
                <li><a href="{{route('evento.index')}}">Actualizar evento</a></li>
                <li><a href="{{route('evento.deleteList')}}">Borrar evento</a></li>
              </ul>
            </li>
            <!-- Cervecerias -->
            <li><a href="#opcionesCerveceria" aria-expanded="false" data-toggle="collapse"><i class="icon-form" ></i>Cervecerías</a>
              <ul id="opcionesCerveceria" class="collapse list-unstyled ">
                <li><a href="{{route('cerveceria.create')}}">Agregar Cervecería</a></li>
                <li><a href="{{route('cerveceria.index')}}">Actualizar Cervecería</a></li>
                <li><a href="{{route('cerveceria.delete')}}">Eliminar Cervecería</a></li>
              </ul>
            </li>
            <!-- Cervecerias -->
            <li><a href="#opcionesCerveza" aria-expanded="false" data-toggle="collapse"> <i class="icon-flask"></i>Cervezas </a>
              <ul id="opcionesCerveza" class="collapse list-unstyled ">
                <li><a href="{{route('cerveza.create')}}">Agregar Cerveza</a></li>
                <li><a href="{{route('cerveza.updateList')}}">Actualizar Cerveza</a></li>
                <li><a href="{{route('cerveza.deleteList')}}">Eliminar Cerveza</a></li>
              </ul>
            </li>
            <li><a href="#pagesDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-line-chart"></i>Reportes </a>
              <ul id="pagesDropdown" class="collapse list-unstyled ">
                <li><a href="{{route('reporte.index')}}">Generar reporte</a></li>
                <li><a href="{{route('reporte.list')}}">Exportar reporte</a></li>
              </ul>
            </li>
            <!--
            <li><a href="#opcionesGenerales" aria-expanded="false" data-toggle="collapse"> <i class="icon-user"></i>Cuenta</a>
              <ul id="opcionesGenerales" class="collapse list-unstyled ">
                <li><a href="#">Actualizar información</a></li>
              </ul>
            </li>
            -->
          </ul>
        </div>
      </div>
    </nav>
    <div class="page">
      <header class="header">
          <nav class="navbar">
            <div class="container-fluid">
              <div class="navbar-holder d-flex align-items-center justify-content-between">
                <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
                    <div class="brand-text d-none d-md-inline-block"><span>CATA</span><strong class="text-primary"> Designer</strong></div></a></div>
                <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                  <!-- Notifications dropdown-->
                  <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell"></i><span class="badge badge-warning">12</span></a>
                    <ul aria-labelledby="notifications" class="dropdown-menu">
                      <li><a rel="nofollow" href="#" class="dropdown-item"> 
                          <div class="notification d-flex justify-content-between">
                            <div class="notification-content"><i class="fa fa-envelope"></i>You have 6 new messages </div>
                            <div class="notification-time"><small>4 minutes ago</small></div>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item"> 
                          <div class="notification d-flex justify-content-between">
                            <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                            <div class="notification-time"><small>4 minutes ago</small></div>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item"> 
                          <div class="notification d-flex justify-content-between">
                            <div class="notification-content"><i class="fa fa-upload"></i>Server Rebooted</div>
                            <div class="notification-time"><small>4 minutes ago</small></div>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item"> 
                          <div class="notification d-flex justify-content-between">
                            <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                            <div class="notification-time"><small>10 minutes ago</small></div>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-bell"></i>view all notifications                                            </strong></a></li>
                    </ul>
                  </li>
                  <!-- Messages dropdown-->
                  <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope"></i><span class="badge badge-info">10</span></a>
                    <ul aria-labelledby="notifications" class="dropdown-menu">
                      <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                          <div class="msg-profile"> <img src="img/avatar-1.jpg" alt="..." class="img-fluid rounded-circle"></div>
                          <div class="msg-body">
                            <h3 class="h5">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                          <div class="msg-profile"> <img src="img/avatar-2.jpg" alt="..." class="img-fluid rounded-circle"></div>
                          <div class="msg-body">
                            <h3 class="h5">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                          <div class="msg-profile"> <img src="img/avatar-3.jpg" alt="..." class="img-fluid rounded-circle"></div>
                          <div class="msg-body">
                            <h3 class="h5">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                          </div></a></li>
                      <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-envelope"></i>Read all messages    </strong></a></li>
                    </ul>
                  </li>
                  <!-- Log out-->
                  <li class="nav-item">
                    <a href="{{route('editor.logout')}}" 
                       class="nav-link logout"
                       onclick="event.preventDefault(); document.getElementById('editor-logout-form').submit();">
                      <span class="d-none d-sm-inline-block">Logout</span>
                      <i class="fa fa-sign-out"></i>
                    </a>
                  </li>
                  <form id="editor-logout-form" action="{{ route('editor.logout') }}" method="POST" style="display: none;">
                    @csrf
                  </form>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        <main>
          @include('layouts_editor.editorAlertas')
          @yield('content')
        </main>
        <footer class="main-footer">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-6">
                <p>CATA &copy; 2020-2023</p>
              </div>
              <div class="col-sm-6 text-right">
                <p>BETA</p>
              </div>
            </div>
          </div>
      </footer>
    </div>
  </body>
</html>