routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Cerveceria;
use App\Cerveza;
use App\Evento;
use App\Editor;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Ruta de inicio
Route::get('/', function(){
    return redirect()->route('inicio');
});

Route::get('/inicio', function() {

    $cervezas = Cerveza::inRandomOrder()->take(10)->get();
    $cervezas = $cervezas->all();

    return view('layouts.content', compact('cervezas'));
})->name('inicio');



//Rutas para el cliente
Route::get('passwd/{cliente}', 'ClienteController@passwd')->name('cliente.passwd');
Route::get('cliente/compra', 'ClienteController@compra')->name('cliente.compra');
Route::get('cliente/checkout/domicilio', 'ClienteController@checkout_dom')->name('cliente.checkout_dom');
Route::get('cliente/checkout/envio', 'ClienteController@checkout_env')->name('cliente.checkout_env');
Route::get('cliente/checkout/pago', 'ClienteController@checkout_pag')->name('cliente.checkout_pag');
Route::get('cliente/checkout/revision', 'ClienteController@checkout_rev')->name('cliente.checkout_rev');
Route::patch('cliente/{id}/password', 'ClienteController@changePassword')->name('cliente.changePassword');
Route::resource('cliente', 'ClienteController');

//Ruta para domicilio
Route::resource('domicilio', 'DomicilioController');

//Ruta para tarjeta
Route::resource('tarjeta', 'TarjetaController');

//Rutas para editor
//Route::get('/editor/updateList', 'EditorController@updateList')->name('editor.updateList');
//Route::get('/editor/deleteList', 'EditorController@deleteList')->name('editor.deleteList');
//Route::post("/editor/scopeName", "EditorController@scopeName")->name("editor.scopeName");
//Route::post("/editor/scopeDelete", "EditorController@scopeDelete")->name("editor.scopeDelete");
//Route::get('editor/login', 'Auth\EditorLoginController@showLoginForm');
//Route::post('editor/login', 'Auth\EditorLoginController@login')->name('editor.login');
//Route::post('editor/logout', 'Auth\EditorLoginController@logout')->name('editor.logout');
//Route::resource('editor', 'EditorController');

//Rutas para libro
//Route::get('/cerveza/update', 'LibroController@updateList')->name('cerveza.updateList');
//Route::get('/cerveza/delete', 'LibroController@deleteList')->name('cerveza.deleteList');

//Route::post("/cerveza/scopeName", "CervezaController@scopeName")->name("cerveza.scopeName");
//Route::post("/cerveza/scopeDelete", "CervezaController@scopeDelete")->name("cerveza.scopeDelete");

Route::resource('libro', 'LibroController');

//Rutas para pedidos
Route::get('/crearPedido', 'PedidoController@crearPedido')->name('pedido.store');
Route::get('/pedidos', 'PedidoController@showOrders')->name('pedido.showOrders');
Route::get('/cliente/{cliente}/{pedido}', 'PedidoController@showOneOrder')->name('pedido.showOneOrder');

//Ruta para enviar correo
//Route::get('/send-mail', 'PedidoController@sendEmail')->name('pedido.sendEmail');


//Rutas para la tienda
Route::get('tienda/cervezas', 'ShopController@porCerveceria')->name('tienda.porCerveceria');
Route::get('estilo/{estilo}', 'ShopController@porEstilo')->name('tienda.porEstilo');
Route::post('tienda/buscar', 'ShopController@buscar')->name('tienda.buscar');
Route::resource('tienda', 'ShopController');

//Ruta para contacto
Route::get('/contacto', function() {

    return view('layouts_cliente.contacto');
});

//Rutsa para el carrito de compras
Route::resource('cart', 'CartController');
Route::post('cart/coupon', 'CartController@apply')->name('cart.apply');
Route::get('vaciar', function(){
    Cart::clear();
});

//Rutas para Eventos
Route::get('/evento/delete/{id}', 'EventoController@delete')->name('evento.delete');
Route::get('/evento/delete', 'EventoController@deleteList')->name('evento.deleteList');
Route::post("/evento/scopeName", "EventoController@scopeName")->name("evento.scopeName");
Route::post("/evento/scopeDelete", "EventoController@scopeDelete")->name("evento.scopeDelete");
Route::resource('evento', 'EventoController');

//Rutas para Reportes
Route::post('/reporte/nuevo', 'ReporteController@createReport')->name('reporte.nuevo');
Route::get('/reporte/create/pdf', 'ReporteController@createPdf')->name('reporte.pdf');
Route::get('/reporte/view', 'ReporteController@view')->name('reporte.view');
Route::get('/reporte/select/{reporte}', 'ReporteController@select')->name('reporte.select');
Route::get('/reportes', 'ReporteController@viewReports')->name('reporte.list');
Route::resource('reporte', 'ReporteController');

resources/views/partials/checkouts/checkoutDomicilio.blade.php
<div class="nav flex-column flex-md-row nav-pills text-center">
  <a href="#" class="nav-link flex-sm-fill text-sm-center active">
      <i class="fa fa-map-marker"></i>Dirección
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-truck"></i>Envío
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-money"></i>Pago
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-eye"></i>Pedido
  </a>
</div>
<div class="content py-3">
  @if($domicilio->id != NULL)
    <div class="row">
      <div class="col-md-6 col-lg-3">
        <div class="form-group">
          <label for="codpos">Código postal</label>
          <input id="codpos" type="text" class="form-control" disabled
          name="codigo_postal" value="{{$domicilio->codigo_postal ?? '' }}">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="estado">Estado</label>
          <input id="estado" type="text" class="form-control" disabled
          name="estado" value="{{$domicilio->estado ?? '' }}">
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="ciudad">Ciudad</label>
          <input id="ciudad" type="text" class="form-control" disabled
          name="ciudad" value="{{$domicilio->ciudad ?? '' }}">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="colonia">Colonia</label>
            <input id="colonia" type="text" class="form-control" disabled
            name="colonia" value="{{$domicilio->colonia ?? '' }}">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="calle_principal">Calle principal</label>
          <input id="calle_principal" type="text" class="form-control" disabled
          name="calle_principal" value="{{$domicilio->calle_principal ?? '' }}">
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="form-group">
          <label for="num_ext">Número exterior</label>
          <input id="num_ext" type="text" class="form-control" disabled
          name="num_ext" value="{{$domicilio->num_ext ?? '' }}">
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="form-group">
          <label for="num_int">Número interior</label>
          <input id="num_int" type="text" class="form-control" disabled
          name="num_int" value="{{$domicilio->num_int ?? '' }}">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="calle1">Calle 1</label>
          <input id="calle1" type="text" class="form-control" disabled
          name="calle1" value="{{$domicilio->calle1 ?? '' }}">
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="calle2">Calle 2</label>
          <input id="calle2" type="text" class="form-control" disabled
          name="calle2" value="{{$domicilio->calle2 ?? '' }}">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label for="comment">Indicaciones adicionales para entregar tus compras en esta dirección
            <span class="required"></span>
          </label>
          <textarea id="referencia" rows="4" class="form-control" disabled
          name="referencia">{{$domicilio->referencia ?? '' }}</textarea>
        </div>
      </div>
    </div>
  @else
    <p class="text-muted">Favor de registrar tu domicilio antes de terminar de procesar el pedido.</p>
    <div class="text-center">
      <a href="{{route('domicilio.index')}}" class="btn btn-primary" disabled>
        <i class="fa fa-save"></i>
        Registra tu domicilio
      </a>
    </div>
  @endif
</div>
<div class="box-footer d-flex justify-content-between">
  <a href="{{route('cart.index')}}" class="btn btn-outline-secondary">
    <i class="fa fa-chevron-left"></i>Regresa al carrito
  </a>
  @if($domicilio->id != NULL)
    <a href="{{route('cliente.checkout_env')}}" class="btn btn-primary" disabled>
      Selecciona forma de envío
      <i class="fa fa-chevron-right"></i>
    </a>
  @endif
</div>

resources/views/partials/checkouts/checkoutEnvio.blade.php
<div class="nav flex-column flex-md-row nav-pills text-center">
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-map-marker"></i>Dirección
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center active">
      <i class="fa fa-truck"></i>Envío
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-money"></i>Pago
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-eye"></i>Pedido
  </a>
</div>
<div class="content py-3">
  <form action="{{route('cliente.checkout_pag')}}" method="GET">
    @if(Session::has('error_message'))
      <div class="alert alert-warning" role="alert">{{Session::get('error_message')}}</div>
    @endif
    <div class="row">
      <div class="col-md-6">
        <div class="box shipping-method">
          <h4>Envío exprés</h4>
          <p>Recibirás tu pedido en un máximo de 3 días hábiles.</p><br><br>
          <p>Costo: $150.00</p>
          <div class="box-footer text-center">
            <input type="radio" name="envio" value="expres" id="envio">
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="box shipping-method">
          <h4>Envío normal</h4>
          <p>Recibirás tu pedido en un máximo de 7 días hábiles.</p><br><br>
          <p>Costo: $100.00</p>
          <div class="box-footer text-center">
            <input type="radio" name="envio" value="normal" id="envio">
          </div>
        </div>
      </div>
    </div>
    <div class="box-footer d-flex justify-content-between">
      <a href="{{route('cliente.checkout_dom')}}" class="btn btn-outline-secondary">
        <i class="fa fa-chevron-left"></i>Regresa a Dirección
      </a>
      <button type="submit" class="btn btn-primary"  id="submit" >
        Selecciona método de pago
        <i class="fa fa-chevron-right"></i>
      </button>
    </div>
  </form>
</div>

resources/views/partials/checkouts/checkoutPago.blade.php
<div class="nav flex-column flex-md-row nav-pills text-center">
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-map-marker"></i>Dirección
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-truck"></i>Envío
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center active">
      <i class="fa fa-money"></i>Pago
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-eye"></i>Pedido
  </a>
</div>
<div class="content py-3">
  <form action="{{route('cliente.checkout_rev')}}" method="GET">
    @if(Session::has('error_message'))
      <div class="alert alert-warning" role="alert">{{Session::get('error_message')}}</div>
    @endif
    <div class="row">
      <div class="col-md-6">
        <div class="box shipping-method">
          <h4>Tarjeta de crédito/débito</h4>
          <p>Realizar tu pago con tarjeta.</p>
          <div class="box-footer text-center">
            <input type="radio" name="pago" value="tarjeta">
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="box shipping-method">
          <h4>PayPal</h4>
          <p>Realizar tu pago a través de PayPal.</p>
          <div class="box-footer text-center">
            <input type="radio" name="pago" value="paypal">
            <input type="hidden" name="envio" value="{{\Request::get('envio')}}">
          </div>
        </div>
      </div>
    </div>
    <div class="box-footer d-flex justify-content-between">
      <a href="{{route('cliente.checkout_env')}}" class="btn btn-outline-secondary">
        <i class="fa fa-chevron-left"></i>Regresa a Envío
      </a>
      <button type="submit" class="btn btn-primary">
        Revisa tu pedido
        <i class="fa fa-chevron-right"></i>
      </button>
    </div>
  </form>
</div>

resources/views/partials/checkouts/checkoutRevision.blade.php
<div class="nav flex-column flex-md-row nav-pills text-center">
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-map-marker"></i>Dirección
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-truck"></i>Envío
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center" disabled>
      <i class="fa fa-money"></i>Pago
  </a>
  <a href="#" class="nav-link flex-sm-fill text-sm-center active">
      <i class="fa fa-eye"></i>Pedido
  </a>
</div>
<div class="content py-3">
  <div class="box">
    @if(Cart::getContent()->count() > 0)
      <p class="text-muted">Tienes {{Cart::getTotalQuantity()}} producto(s) en el carrito</p>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th colspan="2">Producto</th>
              <th>Cantidad</th>
              <th>Precio unitario</th>
              <th>Descuento</th>
              <th colspan="2">Total</th>
            </tr>
          </thead>
          @foreach(Cart::getContent() as $item)
            <tbody>
              <tr>
                <td>
                  <a href="{{route('tienda.show', $item->id)}}">
                    <img src="{{$item->model->imagen}}" alt="$item->model->nombre" class="fit-image">
                  </a>
                </td>
                <td><a href="{{route('tienda.show', $item->id)}}">{{$item->model->nombre}}</a></td>
                <td>{{$item->quantity}}</td>
                <td>${{$item->model->precio}}</td>
                <td>$0.00</td>
                <td>${{$item->getPriceSum()}}</td>
              </tr>
            </tbody>
          @endforeach
          <tfoot>
            <tr>
              <th colspan="5">Total</th>
              <th colspan="2">${{Cart::getSubTotal()}}</th>
            </tr>
          </tfoot>
        </table>
      </div>
    @else
      <p class="text-muted">No tienes productos en el carrito</p>
    @endif
  </div>
</div>
<div class="box-footer d-flex justify-content-between">
  <a href="{{url('cliente/checkout/pago')}}" class="btn btn-outline-secondary">
    <i class="fa fa-chevron-left"></i>Regresa a Pago
  </a>
  <a href="{{route('pedido.store')}}" class="btn btn-primary">
  Finalizar pedido
    <i class="fa fa-chevron-right"></i>
  </a>
</div>