routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Cerveceria;
use App\Cerveza;
use App\Evento;
use App\Editor;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Ruta de inicio
Route::get('/', function(){
    return redirect()->route('inicio');
});

Route::get('/inicio', function() {

    $cervezas = Cerveza::inRandomOrder()->take(10)->get();
    $cervezas = $cervezas->all();

    return view('layouts.content', compact('cervezas'));
})->name('inicio');



//Rutas para el cliente
Route::get('passwd/{cliente}', 'ClienteController@passwd')->name('cliente.passwd');
Route::get('cliente/compra', 'ClienteController@compra')->name('cliente.compra');
Route::get('cliente/checkout/domicilio', 'ClienteController@checkout_dom')->name('cliente.checkout_dom');
Route::get('cliente/checkout/envio', 'ClienteController@checkout_env')->name('cliente.checkout_env');
Route::get('cliente/checkout/pago', 'ClienteController@checkout_pag')->name('cliente.checkout_pag');
Route::get('cliente/checkout/revision', 'ClienteController@checkout_rev')->name('cliente.checkout_rev');
Route::patch('cliente/{id}/password', 'ClienteController@changePassword')->name('cliente.changePassword');
Route::resource('cliente', 'ClienteController');

//Ruta para domicilio
Route::resource('domicilio', 'DomicilioController');

//Ruta para tarjeta
Route::resource('tarjeta', 'TarjetaController');

//Rutas para editor
//Route::get('/editor/updateList', 'EditorController@updateList')->name('editor.updateList');
//Route::get('/editor/deleteList', 'EditorController@deleteList')->name('editor.deleteList');
//Route::post("/editor/scopeName", "EditorController@scopeName")->name("editor.scopeName");
//Route::post("/editor/scopeDelete", "EditorController@scopeDelete")->name("editor.scopeDelete");
//Route::get('editor/login', 'Auth\EditorLoginController@showLoginForm');
//Route::post('editor/login', 'Auth\EditorLoginController@login')->name('editor.login');
//Route::post('editor/logout', 'Auth\EditorLoginController@logout')->name('editor.logout');
//Route::resource('editor', 'EditorController');

//Rutas para libro
//Route::get('/cerveza/update', 'LibroController@updateList')->name('cerveza.updateList');
//Route::get('/cerveza/delete', 'LibroController@deleteList')->name('cerveza.deleteList');

//Route::post("/cerveza/scopeName", "CervezaController@scopeName")->name("cerveza.scopeName");
//Route::post("/cerveza/scopeDelete", "CervezaController@scopeDelete")->name("cerveza.scopeDelete");

Route::resource('libro', 'LibroController');

//Rutas para pedidos
Route::get('/crearPedido', 'PedidoController@crearPedido')->name('pedido.store');
Route::get('/pedidos', 'PedidoController@showOrders')->name('pedido.showOrders');
Route::get('/cliente/{cliente}/{pedido}', 'PedidoController@showOneOrder')->name('pedido.showOneOrder');

//Ruta para enviar correo
//Route::get('/send-mail', 'PedidoController@sendEmail')->name('pedido.sendEmail');


//Rutas para la tienda
Route::get('tienda/cervezas', 'ShopController@porCerveceria')->name('tienda.porCerveceria');
Route::get('estilo/{estilo}', 'ShopController@porEstilo')->name('tienda.porEstilo');
Route::post('tienda/buscar', 'ShopController@buscar')->name('tienda.buscar');
Route::resource('tienda', 'ShopController');

//Ruta para contacto
Route::get('/contacto', function() {

    return view('layouts_cliente.contacto');
});

//Rutsa para el carrito de compras
Route::resource('cart', 'CartController');
Route::post('cart/coupon', 'CartController@apply')->name('cart.apply');
Route::get('vaciar', function(){
    Cart::clear();
});

//Rutas para Eventos
Route::get('/evento/delete/{id}', 'EventoController@delete')->name('evento.delete');
Route::get('/evento/delete', 'EventoController@deleteList')->name('evento.deleteList');
Route::post("/evento/scopeName", "EventoController@scopeName")->name("evento.scopeName");
Route::post("/evento/scopeDelete", "EventoController@scopeDelete")->name("evento.scopeDelete");
Route::resource('evento', 'EventoController');

//Rutas para Reportes
Route::post('/reporte/nuevo', 'ReporteController@createReport')->name('reporte.nuevo');
Route::get('/reporte/create/pdf', 'ReporteController@createPdf')->name('reporte.pdf');
Route::get('/reporte/view', 'ReporteController@view')->name('reporte.view');
Route::get('/reporte/select/{reporte}', 'ReporteController@select')->name('reporte.select');
Route::get('/reportes', 'ReporteController@viewReports')->name('reporte.list');
Route::resource('reporte', 'ReporteController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome/all.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/blog.blade.php
<!--
*** BLOG HOMEPAGE ***
_________________________________________________________
-->
        <div class="box text-center">
            <div class="container">
                <div class="col-md-12">
                    <h3 class="text-uppercase">From our blog</h3>
                    <p class="lead mb-0">What's new in the world of fashion? <a href="blog.html">Check our blog!</a></p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-md-12">
                <div id="blog-homepage" class="row">
                    <div class="col-sm-6">
                        <div class="post">
                            <h4><a href="post.html">Fashion now</a></h4>
                            <p class="author-category">By <a href="#">John Slim</a> in <a href="">Fashion and style</a></p>
                            <hr>
                            <p class="intro">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                            <p class="read-more"><a href="post.html" class="btn btn-primary">Continue reading</a></p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="post">
                            <h4><a href="post.html">Who is who - example blog post</a></h4>
                            <p class="author-category">By <a href="#">John Slim</a> in <a href="">About Minimal</a></p>
                            <hr>
                            <p class="intro">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
                            <p class="read-more"><a href="post.html" class="btn btn-primary">Continue reading</a></p>
                        </div>
                    </div>
                </div> <!-- /#blog-homepage-->
            </div>
        </div> <!-- /.container-->
        <!-- *** BLOG HOMEPAGE END ***-->
    </div>
</div>

resources/views/layouts/checkout.blade.php
@extends('layouts.header')

@section('content')
<div id="all">
  <div id="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{route('cliente.index')}}">Inicio</a></li>
              <li aria-current="page" class="breadcrumb-item active">Checkout - Dirección</li>
            </ol>
          </nav>
        </div>
        <div id="checkout" class="col-lg-9">
          <div class="box">
            @if(\Request::is('cliente/checkout/domicilio'))
              @include('partials.checkouts.checkoutDomicilio')
            @elseif(\Request::is('cliente/checkout/envio'))
              @include('partials.checkouts.checkoutEnvio')
            @elseif(\Request::is('cliente/checkout/pago'))
              @include('partials.checkouts.checkoutPago')
            @elseif(\Request::is('cliente/checkout/revision'))
              @include('partials.checkouts.checkoutRevision')
            @endif
          </div>
        </div>
        <div class="col-md-3">
          <div id="order-summary" class="card">
            <div class="card-header">
              <h4 class="mt-4 mb-4">Resumen de pedido</h4>
            </div>
            <div class="card-body">
              <p class="text-muted">El costo de envío sera añadido cuando seleccione el método de envío.</p>
              <div class="table-responsive">
                <table class="table">
                  <tbody>
                    <tr>
                      <td>Subtotal</td>
                      <th>${{Cart::getSubTotal()}}</th>
                    </tr>
                    <tr>
                    <tr>
                      <td>Envío</td>
                      @if(null !== Cart::getCondition('envio'))
                        <th>{{Cart::getCondition('envio')->getAttributes()['format']}}</th>
                      @else
                        <th>$0.00</th>
                      @endif
                    </tr>
                    <tr class="total">
                      <td>Total</td>
                      <th>${{Cart::getTotal()}}</th><!--${{Cart::getTotal()}}-->
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/layouts/content.blade.php
@extends('layouts.header')

@section('content')
<div id="all">
  <div id="content">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="main-slider" class="owl-carousel owl-theme">
            <div class="item"><img src="img/img-index1.gif" alt="" class="img-fluid"></div>
            <div class="item"><img src="img/img-index3.gif" alt="" class="img-fluid"></div>
            <div class="item"><img src="img/img-index4.gif" alt="" class="img-fluid"></div>
          </div>
        </div>
      </div>
    </div>
    <!--*** ADVANTAGES HOMEPAGE ***-->
    <div id="advantages">
      <div class="container">
        <div class="row mb-4">
          <div class="col-md-4">
            <div class="box d-flex flex-column justify-content-center mb-0 h-100">
              <div class="icon"><i class="fa fa-heart"></i></div>
              <h3><a href="#">Elige lo que quieras</a></h3>
              <p class="mb-0">Selecciona tus cervezas artesanales y agrégalas al carrito de compras.</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="box d-flex flex-column justify-content-center mb-0 h-100">
              <div class="icon"><i class="fa fa-tags"></i></div>
              <h3><a href="#">Los mejores precios</a></h3>
              <p class="mb-0">Contamos con una amplia variedad de cervezas artesanales mexicanas e importadas a un excelente precio.</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="box d-flex flex-column justify-content-center mb-0 h-100">
              <div class="icon"><i class="fa fa-thumbs-up"></i></div>
              <h3><a href="#">No esperes mucho</a></h3>
              <p class="mb-0">En máximo 7 días hábiles recibirás el pedido en la puerta de tu casa</p>
            </div>
          </div>
        </div>
      </div>
    </div><!-- *** ADVANTAGES END ***-->
    @include('layouts.products-section')
    <!-- el include blog -->
@endsection

resources/views/layouts/footer.blade.php
<footer>
  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <h4 class="mb-3">Pages</h4>
          <ul class="list-unstyled">
            <li><a href="text.html">About us</a></li>
            <li><a href="text.html">Terms and conditions</a></li>
            <li><a href="faq.html">FAQ</a></li>
            <li><a href="contact.html">Contact us</a></li>
          </ul>
          <hr>
          <h4 class="mb-3">User section</h4>
          <ul class="list-unstyled">
            <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
            <li><a href="register.html">Regiter</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6">
          <h4 class="mb-3">Top categories</h4>
          <h5>Men</h5>
          <ul class="list-unstyled">
            <li><a href="category.html">T-shirts</a></li>
            <li><a href="category.html">Shirts</a></li>
            <li><a href="category.html">Accessories</a></li>
          </ul>
          <h5>Ladies</h5>
          <ul class="list-unstyled">
            <li><a href="category.html">T-shirts</a></li>
            <li><a href="category.html">Skirts</a></li>
            <li><a href="category.html">Pants</a></li>
            <li><a href="category.html">Accessories</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6">
          <h4 class="mb-3">Where to find us</h4>
          <p>
            <strong>Obaju Ltd.</strong>
            <br>13/25 New Avenue<br>New Heaven<br>45Y 73J<br>England<br>
            <strong>Great Britain</strong>
          </p>
          <a href="contact.html">Go to contact page</a>
          <hr class="d-block d-md-none">
        </div>
        <div class="col-lg-3 col-md-6">
          <h4 class="mb-3">Get the news</h4>
          <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
          <form>
            <div class="input-group">
              <input type="text" class="form-control"><span class="input-group-append">
                <button type="button" class="btn btn-outline-secondary">Subscribe!</button></span>
            </div>
          </form>
          <hr>
          <h4 class="mb-3">Stay in touch</h4>
          <p class="social"><a href="#" class="facebook external"><i class="fa fa-facebook"></i></a><a href="#" class="twitter external"><i class="fa fa-twitter"></i></a><a href="#" class="instagram external"><i class="fa fa-instagram"></i></a><a href="#" class="gplus external"><i class="fa fa-google-plus"></i></a><a href="#" class="email external"><i class="fa fa-envelope"></i></a></p>
        </div>
      </div>
    </div>
  </div>
  <div id="copyright">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-2 mb-lg-0">
          <p class="text-center text-lg-left">©2019 Your name goes here.</p>
        </div>
        <div class="col-lg-6">
          <p class="text-center text-lg-right">Template design by <a href="https://bootstrapious.com/">Bootstrapious</a>
            <!-- If you want to remove this backlink, pls purchase an Attribution-free License @ https://bootstrapious.com/p/obaju-e-commerce-template. Big thanks!-->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CATA online</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700">
    <!-- owl carousel-->
    <link rel="stylesheet" href="/vendor/owl.carousel/assets/owl.carousel.css">
    <link rel="stylesheet" href="/vendor/owl.carousel/assets/owl.theme.default.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="/favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    
    <!-- JavaScript files-->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js"></script>
    <script src="/js/front.js"></script>

    @stack('script-update-cart')
  </head>
  <body>
    <!-- navbar-->
    <header class="header mb-5">
      <!--TOPBAR-->
      <div id="top">
        <!-- LOGIN AND REGISTRATION -->
        @include('partials.login-register')
        <!-- LOGIN MODAL -->
        @include('partials.login-client')
      </div><!-- *** TOP BAR END ***-->
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          @include('partials.logo')
          <div id="navigation" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              @guest
                <li class="nav-item"><a href="{{route('inicio')}}" class="nav-link">Inicio</a></li>
              @else
                <li class="nav-item"><a href="{{route('cliente.index')}}" class="nav-link">Inicio</a></li>
              @endguest
              <li class="nav-item"><a href="{{route('tienda.index')}}" class="nav-link">tienda</a></li>
              @include('partials.menus.estilos-menu')
            </ul>
            @include('partials.navbar-buttons')
          </div>
        </div>
      </nav>
      @include('partials.search')
    </header>
    <main>
      @yield('content')
    </main>
    @include('layouts.footer')
  </body>
</html>

resources/views/layouts/products-section.blade.php
<div id="hot">
  <div class="box py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="mb-0">lo mejor</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="product-slider owl-carousel owl-theme">
      @foreach($cervezas as $cerveza)
      <div class="item">
        <div class="product">
          <div class="flip-container">
            <div class="flipper">
              <div class="front"><a href="{{route('tienda.show', $cerveza->id)}}"><img src="{{$cerveza->imagen}}" alt="" class="img-fluid"></a></div>
              <div class="back"><a href="{{route('tienda.show', $cerveza->id)}}"><img src="{{$cerveza->imagen}}" alt="" class="img-fluid"></a></div>
            </div>
          </div>
          <a href="{{route('tienda.show', $cerveza->id)}}" class="invisible"><img src="{{$cerveza->imagen}}" alt="" class="img-fluid"></a>
          <div class="text">
            <h3><a href="{{route('tienda.show', $cerveza->id)}}">{{$cerveza->nombre}}</a></h3>
            <p class="price"> 
              <del></del>${{$cerveza->precio}}
            </p>
          </div>
        </div>
      </div>
      @endforeach
    </div>
    <div class="row justify-content-center">
      <p class="loadMore">
        <a href="{{route('tienda.index', ['block' => 1, 'page' => 1])}}" class="btn btn-primary btn-lg">
          Mostrar todo
        </a>
      </p>
    </div>
  </div>
</div>